clear all, close all, clc
%% Import the data

addpath(genpath('./Data'))
load('Indian_pines_gt.mat');

%% Plot the ground truth

n_colors = length(unique(indian_pines_gt(indian_pines_gt~=0)));

my_colors = [255 255 255;
             100 200 255;
             255 140 0;
             255 200 0;
             255 255 0;
             50  200 50;
             0   128 0;
             120 255 0;
             160 40 40;
             128 0   128;
             255 100 70;
             255 160 120;
             255 0   0;
             255 20  150;
             0   0   128;
             0   0   0;
             170 170 170]/255;

figure('WindowState','maximized');
colormap(my_colors)
imagesc(indian_pines_gt)
colorbar('Ticks',[1+0.5*(n_colors-1)/n_colors:(n_colors-1)/n_colors:n_colors],...
         'TickLabels',{'Alfalfa',...
                       'Corn-notill',...
                       'Corn-mintill',...
                       'Corn',...
                       'Grass-pasture',...
                       'Grass-trees',...
                       'Grass-pasture-mowed',...
                       'Hay-windrowed',...
                       'Oats',...
                       'Soybean-notill',...
                       'Soybean-mintill',...
                       'Soybean-clean',...
                       'Wheat',...
                       'Woods',...
                       'Buildings-Grass-Trees-Drives',...
                       'Stone-Steel-Towers'},...
          'FontSize',14)
title('Ground Truth','FontSize',14)
axis equal; axis off

saveas(gcf,'./Images/Indian_Pines_GroundTruth.png')